name: form_builder_map_field
description: Map Input Field for flutter_form_builder package. Used to select coodinates on a map.
version: 0.0.1
homepage: https://github.com/danvick/form_builder_map_field

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.0.0
  google_maps_flutter: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
